name = "career-coach"
version = "1.0.0"
type = "web"
production_host = "indigo-lobster-darcee-7vsm4gka.bls.dev"

[deployment]
permission = "public"
nodes = 1
permissions = [ "https://generativelanguage.googleapis.com/" ]

[build]
dir = "build"
entry = "debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "release.wasm"
command = "npm run build:release"

[[deployments]]
name = "blessnet"
description = ""
cid = "bafybeianekcnhcjcjrautiyl4tnelnlfhjs443hncqpsvajkzpy7ohaswm"
created = "2025-05-28T06:14:16.221Z"

  [deployments.runtime]
  url = "blessnet.tar.gz"
  checksum = "50e628ab6ae68c1ee4711f362a0909663e4591ff9b8abfd711a15f23f2e48892"
