name = "career-coach"
version = "1.0.0"
type = "web"
production_host = "moccasin-whippet-daisie-z5tdt5rq.bls.dev"

[deployment]
permission = "public"
nodes = 1
permissions = [
  "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=AIzaSyDNeMYy5q3mGJv7-Bj6KMwPmDL6f51RJ9s"
]

[build]
dir = "build"
entry = "debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "release.wasm"
command = "npm run build:release"

[[deployments]]
name = "blessnet"
description = ""
cid = "bafybeie4x3q4q7dsfx7d6vtcx2og73xodrxz27hmz3t24tibjvz5tdt5rq"
created = "2025-05-18T22:21:06.882Z"

  [deployments.runtime]
  url = "blessnet.tar.gz"
  checksum = "55bea6f7e14a5904b960bdc4cb0d69108187ae7dca7eaec99a5fd5cba44e1a7e"
