name = "career-coach"
version = "1.0.0"
type = "web"
production_host = "indigo-lobster-darcee-7vsm4gka.bls.dev"

[deployment]
permission = "public"
nodes = 1
permissions = [ "https://generativelanguage.googleapis.com/" ]

[build]
dir = "build"
entry = "debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "release.wasm"
command = "npm run build:release"

[[deployments]]
name = "blessnet"
description = ""
cid = "bafybeigbedl7ipmjliqkhxwu6q3jvgflpyobhwf7jcaowagijwngp6zl2m"
created = "2025-05-27T08:07:32.158Z"

  [deployments.runtime]
  url = "blessnet.tar.gz"
  checksum = "6543605472f3566a28b74613dbcd1cfffa4f6e6262ca15d9dd3f40a59ed0f814"
