name = "career-coach"
version = "1.0.0"
type = "web"
production_host = "indigo-lobster-darcee-7vsm4gka.bls.dev"

[deployment]
permission = "public"
nodes = 1
permissions = [ "https://generativelanguage.googleapis.com/" ]

[build]
dir = "build"
entry = "debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "release.wasm"
command = "npm run build:release"

[[deployments]]
name = "blessnet"
description = ""
cid = "bafybeifbbiquhytzldscxamfmwvh4i74luzixwdztluykzzpgxspt5uq4e"
created = "2025-05-28T06:30:23.554Z"

  [deployments.runtime]
  url = "blessnet.tar.gz"
  checksum = "0675d0790de44bd98c2b6de98bc701abacf7f6ef75fc937bbc1398a36ccf4017"
