name = "career-coach"
version = "1.0.0"
type = "web"
production_host = "copper-sloth-nelle-q72biudu.bls.dev"

[deployment]
permission = "public"
nodes = 1
permissions = [ "https://generativelanguage.googleapis.com/" ]

[build]
dir = "build"
entry = "debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "release.wasm"
command = "npm run build:release"

[[deployments]]
name = "blessnet"
description = ""
cid = "bafybeihtcx2pxbgisroxrmvqwpwmi72q6eosldfkdyvgeozv7fvajz6z3q"
created = "2025-06-02T13:52:00.693Z"

  [deployments.runtime]
  url = "blessnet.tar.gz"
  checksum = "ccdda370a24635550ae617a15563c6ecc308a7b795b62f3ac4a7d87abcd493e4"
